name: yala
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  connectivity_plus: ^7.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  equatable: ^2.0.8
  firebase_analytics: ^12.4.2
  firebase_core: ^4.10.0
  firebase_crashlytics: ^5.2.3
  firebase_remote_config: ^6.5.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  flutter_secure_storage: ^10.3.1
  flutter_svg: ^2.3.0
  get_it: ^9.2.1
  go_router: ^17.2.3
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito_black.ttf
          weight: 900
        - asset: assets/fonts/nunito_blackitalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/nunito_extrabold.ttf
          weight: 800
        - asset: assets/fonts/nunito_extrabolditalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito_bold.ttf
          weight: 700
        - asset: assets/fonts/nunito_bolditalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito_semibold.ttf
          weight: 600
        - asset: assets/fonts/nunito_semibolditalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/nunito_medium.ttf
          weight: 500
        - asset: assets/fonts/nunito_mediumitalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito_regular.ttf
          weight: 400
        - asset: assets/fonts/nunito_italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/nunito_light.ttf
          weight: 300
        - asset: assets/fonts/nunito_lightitalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito_extralight.ttf
          weight: 200
        - asset: assets/fonts/nunito_extralightitalic.ttf
          weight: 200
          style: italic